### ISSUE TITLE
Mod seems to be broken for 1.20.5

### ISSUE THREAD

**Issue by KermaHillway** [ADHDMC/InvisibleFrames#4]
I tested your mod and it seems to be completely broken. I play a mostly vanilla modpack with a few quality of life features, none should effect the item frames or the mod. When instealled, item frames are visable but the items inside are not. This may be the case in one dimension, but in another it works almost perfectly and it switches between them in some cases. Glowing item frames sometimes "fixed" the issue but breaks as well if you leave the dimension the item frame is in. It is quite inconsistant. I use curseforge and played on version 1.20.5 Forge

**Comment by Peashooter101** [comment]
We do not develop this on 1.20.5 Forge.

This project is for a Minecraft Plugin, requiring the server software Paper (A fork of Bukkit).

Closed.
